environment:
  type: MaGathering
  num_agents: 3
  grid_size: [20, 20]
  num_resources: 4

args:
  agent_type: QSSBeliefVAE
  seed: 42
  obs_shape: [1, 27]
  state_shape: [1, 27]
  state_shape_unobserved: [1, 14]
  hidden_dim: 64
  latent_dim: 16
  num_belief_samples: 2
  belief_dim: 28 # Keep same as unobserved part * 2 (incl var)
  belief_temperature: 0.5
  num_actions: 5
  num_agents: 3
  q_lr: 0.001
  belief_lr: 0.001
  tau: 0.005
  episodes: 15000
  memory_length: 10000
  gamma: 0.99
  max_steps_per_episode: 100
  batch_size: 32
  epsilon: 0.6 
  qss_lr: 0.001
  f_lr: 0.001
  lambda_f: 0.1
